name: Build and Publish Go Challenge
 
on: 
  push:
  workflow_dispatch: 

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      # Required for uploading code scanning.
      security-events: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Debug - show directory
        run: ls -R *

      - name: Cache Go modules and build cache
        uses: actions/cache@v3
        with:
          # chemins à mettre en cache
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          # générer la clé à partir du hash de go.sum
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          # clés de repli en cas de miss
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22.12

      - name: Build challenge.go
        run: |
          cd Go_Challenge
          go mod init challenge || true  # au cas où le go.mod n’existe pas
          go build -v -o challenge challenge.go

      - name: Setup JFrog CLI with OIDC
        uses: jfrog/setup-jfrog-cli@v4
        with:
          oidc-provider-name: github
          custom-server-id: artifactory-prod
          oidc-audience: jfrog-github
        env:
          JF_URL: https://trialsar.jfrog.io
          JFROG_CLI_AVOID_NEW_VERSION_WARNING: true
         
      - name: Collect environment variables for Build Info
        run: |
          jf rt bce "go-challenge-build" "${{ github.run_number }}"

      - name: Upload binary to Artifactory
        run: |
          cd Go_Challenge
          jf rt upload "challenge" "go-local/challenge-go/${{ github.sha }}/" \
            --build-name="go-challenge-build" \
            --build-number="${{ github.run_number }}"

      - name: Publish Build Info
        run: |
          jf rt bp "go-challenge-build" "${{ github.run_number }}"

      - name: Scan build with Xray
        run: |
          jf bs "go-challenge-build" "${{ github.run_number }}"
          
      
