name: Build & Deploy Go Project

on:
  push:
  workflow_dispatch:

jobs:
  build:
    name: Compile Challenge_GO/challenge.go
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Build challenge.go
        run: |
          cd Challenge_GO
          go build -v -o challenge challenge.go

      - name: Show output binary
        run: ls -lh Challenge_GO/challenge 

